services:
  - type: web
    name: cineforge-api
    env: node
    rootDir: .
    buildCommand: npm install && npm run build --workspace apps/api
    startCommand: npm run start --workspace apps/api
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: APP_URL
        sync: false
      - key: API_URL
        sync: false
      - key: WEB_URL
        sync: false
      - key: ADMIN_EMAIL
        value: admin@cineforge.ai
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
  - type: web
    name: cineforge-web
    env: node
    rootDir: .
    buildCommand: npm install && npm run build --workspace apps/web
    startCommand: npm run start --workspace apps/web
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_WEB_URL
        sync: false
